### ISSUE TITLE
Pseudo classes that require double colon syntax do not parse correctly

### ISSUE THREAD

**Issue by nijk** [Jarzka/stylefy#23]
Stylefy:
```clojure
[span (use-style {::stylefy/mode {::before {:content "'foo'"}}})]
 ```

Actual:
```css
._stylefy_1435390636 before {
  content: 'foo';
}
```

Expected:
```css
._stylefy_1435390636::before {
  content: 'foo';
}
```
