### ISSUE TITLE
Is @font-face working?

### ISSUE THREAD

**Issue by nijk** [Jarzka/stylefy#25]
I'm probably being daft but I can't get `@font-face` rules working in Stylefy. Can you point to a working example?

**Comment by nijk** [comment]
I see this in `<style id="_stylefy-constants-styles_>`

```css
@font-face {
  font-family: OpenSans;
  src: url('font/OpenSans-Regular.ttf') format('ttf');
}

body {
  font-size: 1.6rem;
  line-height: 1.5;
  color: #262626;
  font-family: OpenSans, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

But the browser does not download the ttf file. When I access the URL `http://localhost:8080/font/OpenSans-Regular.ttf` the font is downloaded by the browser.

This might well be something really daft I'm doing with my styling but I can't see what's wrong here. Any ideas?
