### ISSUE TITLE
Support styling based on ancestor class (.parent &)

### ISSUE THREAD

**Issue by shanberg** [Jarzka/stylefy#59]
A common issue in component styling is the ability to modify the style of the current object based on the state of one of its ancestors.

```css
.my-component { color: blue }
.os-macos .my-component { color: green }
.os-windows .my-component { color: orange }
```

The `&` selector seems to only implement part of the traditional SCSS/Less featureset. I can use it to create selectors like `&:hover` -> `.my-component:hover`, but not `:hover > &` -> `:hover > .mycomponent`.

I haven't been able to replicate this kind of styling workflow using stylefy.

**Comment by Jarzka** [comment]
Have you tried using stylefy's manual mode to write this kind of selector manually? Manual mode can be used to write custom CSS using [Garden syntax.](https://github.com/noprompt/garden#syntax). The parent selector is also supported in Garden:

> As in Less/Sass, Garden also supports selectors prefixed with the & character allowing you to reference a parent selector:

**Comment by shanberg** [comment]
@Jarzka 

Here's what I get with manual mode and when using garden selector:

```cljs
(def my-component-style
  {:color "red"
   ::stylefy/manual [[(selectors/& :.test) {:color "blue"}]
                     [(:.test selectors/&) {:color "blue"}]
                     ["&.test" {:color "blue"}]
                     [".test &" {:color "blue"}]]})
```
which evaluates to:

```css
._stylefy_2087609553 {
    color: red;
}
._stylefy_2087609553.test {
    color: blue;
}
._stylefy_2087609553.test {
    color: blue;
}
._stylefy_2087609553 .test & {
    color: blue;
}
```

and what I need instead is

```css
.test ._stylefy_2087609553 {
    color: blue;
}
```

I'm currently working around this by adding classes directly to the component, but there are potentially very many cases where I'd like to use this format, and subscribing to the same data in many parts of our application is pretty hairy.

**Comment by Jarzka** [comment]
I see, stylefy scopes manually written selectors inside the current component, so there is really no (easy) way to select anything outside of it. This is a design choice, and for the most part I see it as a benefit, because it helps keeping styles scoped locally to the current component.

However, perhaps it would be handly to override the default scoping - maybe there should be an option to define the current scope of the style. I have to think about this.

**Comment by Jarzka** [comment]
I have been thinking of a possible solution for this.

Media queries are used to create a new scope for the style, i.e. we define a style which is activated when the defined media query is active. We could use the same idea with custom scopes; we define a style which is activated when the defined scope (CSS selector) is active.

For example: (not implemented anywhere, just an idea):

```clj
(def style-map
  {:color :grey
   ::stylefy/scope [[[:.os-macos] {:color "blue"}]]
                    [[:.os-windows] {:color "purple"}]]]})
```

`::stylefy/scope` should be a collection of **scopes**. A **scope** is a vector in which:
- The first element is a CSS selector, in which the autogenerated stylefy class name is automatically appended (I'm not sure if this is trivial with complex selectors)
- The second element is a style map which is used for the current scope

The output CSS would look like this:

```css
._stylefy_xxxxxxx {
    color: grey;
}

.os-macos ._stylefy_xxxxxxx {
    color: blue;
}

.os-windows ._stylefy_xxxxxxx {
    color: purple;
}
```

What do you think about this?

**Comment by shanberg** [comment]
> Maybe we should only accept simple selectors, like "inside class A which is inside element B"

This makes me a little nervous. It sounds like the following nesting would be impossible:
```cljs
(def style-map
  {:color "red"
   ::stylefy/scope [[[:.os-macos] {:color "blue"}
                     [:.close-button {:color "yellow"}]]
                    [[:.os-windows] {:color "yellow"}
                     [:.close-button {:color "blue"}]]]})
```

And perhaps I'd have to create separate maps like `(def close-button-style)` with the same set of scopes to handle this case.

Would manual-style selectors be available in scopes, e.g.?
```cljs
(def style-map
  {:color "red"
   ::stylefy/scope [[".os-macos > .app-toolbar:hover"] {:color "green"}]})
```

...

Ultimately, virtually any limit on selector complexity will become a future pain point, but a limited solution would get me past my current roadblock, and I'll be grateful for that.

**Comment by Jarzka** [comment]
> Ultimately, virtually any limit on selector complexity will become a future pain point

This is true. Limiting selector complexity would solve simple cases, but there will be cases in which simple selectors are simply not good enough.

> Would manual-style selectors be available in scopes, e.g.?

This could be good way to begin with. I have also been thinking of enabling support for manual-style selectors when using stylefy's manual mode, since some folks may find it easier / more advanced than writing Garden-selectors.

Since Garden uses vector-based selectors, I think we can simplify the scope syntax a bit when using string selectors. The first element in **scope** vector could be string selector:

```clj
(def style-map
  {:color "red"
   ::stylefy/scope [[".os-macos > .app-toolbar:hover" {:color "green"}]
                                [".os-windows > .app-toolbar:hover" {:color "blue"}]]})
```

Later, if I find a good way to support Garden selectors, it would be easy to check the first element of the **scope** vector: if it is a string, we are using manual style, if it is a vector, it is a Garden selector.

**Comment by Jarzka** [comment]
About Garden syntax support. I think it should be possible to achieve with the following algorithm:

- Check every item in the Garden vector
- If you find a style map, wrap it with the current class name

So this:

```clj
{:color "red"
 ::stylefy/scope [[:.os-macos {:color "blue"}]
                  [:.os-windows {:color "yellow"}
                  [:.what [:.ever {:color "purple"}]]]]}
````

Would end up looking like this after the conversion:

```clj
{:color "red"
 ::stylefy/scope [[:.os-macos [:._stylefy_xxxxxx {:color "blue"}]]
                  [:.os-windows [:._stylefy_xxxxxx  {:color "yellow"}]
                  [:.what [:.ever [:._stylefy_xxxxxx {:color "purple"}]]]]]}
```

Which would end up like this in CSS:

```clj
.os-macos ._stylefy_xxxxxx {
  color: blue;
}

.os-windows ._stylefy_xxxxxx {
  color: yellow;
 }

.what .ever ._stylefy_xxxxxx {
  color: purple;
}
```

**Comment by shanberg** [comment]
This looks like an improvement to me.

It looks like `stylefy/scope` is always prepending a set of selectors to the autogenerated classname. Is it possible to also append selectors, e.g. to return this: `.os-windows ._stylefy_xxxxx .child-of_stylefy_xxxxx { color: blue }`?

What I'm accustomed to is being able to use `&` in any part of a nested selector to represent the parent selector, so I'm most excited by whatever gets me closest to that behavior.

**Comment by Jarzka** [comment]
I do not think this would be possible with the currently designed implementation; the autogenerated class name would always be the last element in the CSS selector. Child elements could still be scoped separately.

Also, I'm not sure if it is a good idea to use autogenerated class names in CSS selectors since those names can easily change. It would be a better idea to attach additional "human readable" to your elements and refer to them instead.

**Comment by Jarzka** [comment]
I got a little bit of time to create a minimal implementation of this feature. It's available on the `feature/scope` branch. It works as told in my previous post, except that the scoped style map does not yet support stylefy's special keywords.

**Comment by Jarzka** [comment]
Vendor prefixes, `::stylefy/mode` and `::stylefy/manual` can now be used inside scoped style map:

```clj
(def style-only-in-scoped-box
  {:font-weight :bold
   ::stylefy/scope [[:.scoped-box {:color "red"
                                   ::stylefy/mode {:hover {:color "yellow"}}
                                   ::stylefy/manual [[:.green-text-in-scoped-box {:color "green"}]]}]]})
```

This is still pretty much experimental work and should not be used in production. Still, it would be nice to get some feedback. :)

**Comment by shanberg** [comment]
I'm having difficulty building this locally to give it a rigorous test, but I'm happy with the syntax you've described and the examples you've demonstrated. This looks like it entirely covers my use cases.

Thanks so much for pursuing this.

**Comment by Jarzka** [comment]
I think you should be able to test it by cloning the repo, switching to `feature/scope` branch and running `lein install`. After that, you should be able to require `[stylefy/reagent "3.1.0-SNAPSHOT"]`

**Comment by shanberg** [comment]
I've just tested it and it’s working great so far. It’s a relief to be able to set a few classes at the app root and use them much farther down.

**Comment by Jarzka** [comment]
Scoping now supports media queries. You can write them either inside the scoping query, or have a `::stylefy/media` style definition with scoping rules. The CSS output is a bit different, but the end result is the same

```clj
{:font-weight :bold
   ::stylefy/scope [[:.scoped-box {:color "red"
                                   ::stylefy/mode {:hover {:color "yellow"}}
                                   ::stylefy/manual [[:.special-text-in-scoped-box {:color "green"}]
                                                     (at-media {:max-width "500px"} [:.special-text-in-scoped-box {:color "purple"}])]}]]}
```

Output

```css
._stylefy_-281407580 {
    font-weight: bold;
}

.scoped-box ._stylefy_-281407580 {
    color: red;
}

.scoped-box ._stylefy_-281407580:hover {
    color: yellow;
}

.scoped-box ._stylefy_-281407580 .special-text-in-scoped-box {
    color: green;
}

@media (max-width: 500px) {
    .scoped-box ._stylefy_-281407580 .special-text-in-scoped-box {
        color: purple;
    }
}
```

OR

```clj
{:font-weight :bold
   ::stylefy/media {{:max-width "500px"}
                    {::stylefy/scope [[:.scoped-box {::stylefy/manual [[:.special-text-in-scoped-box {:color "purple"}]]}]]}}
   ::stylefy/scope [[:.scoped-box {:color "red"
                                   ::stylefy/mode {:hover {:color "yellow"}}
                                   ::stylefy/manual [[:.special-text-in-scoped-box {:color "green"}]]}]]}
```

Outputs:

```css
._stylefy_-646023592 {
    font-weight: bold;
}

.scoped-box ._stylefy_-646023592 {
    color: red;
}

.scoped-box ._stylefy_-646023592:hover {
    color: yellow;
}

.scoped-box ._stylefy_-646023592 .special-text-in-scoped-box {
    color: green;
}

@media (max-width: 500px) {
    ._stylefy_-646023592 {}
}

@media (max-width: 500px) {
    .scoped-box ._stylefy_-646023592 {}
    .scoped-box ._stylefy_-646023592 .special-text-in-scoped-box {
        color: purple;
    }
}
```
